/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAO;
import Model.BorrowBook;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VietNguyen
 */
public class BorrowBooksManagementPanel extends javax.swing.JPanel {
    


    public BorrowBooksManagementPanel() {
        initComponents();
    }
    
    /**
     *
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_muonSach = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jb_MaSV = new javax.swing.JLabel();
        jB_MaS = new javax.swing.JLabel();
        txt_MaSV = new javax.swing.JTextField();
        txt_MaS = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_lamMoi = new javax.swing.JButton();
        btn_TaoPhieu = new javax.swing.JButton();
        btn_traSach = new javax.swing.JButton();
        btn_TimKiem = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBorrowBook = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jB_muonSach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jB_muonSach.setText("PHIẾU ĐĂNG KÝ MƯỢN SÁCH:");

        jb_MaSV.setText("Mã SV:");

        jB_MaS.setText("Mã Sách:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_MaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_MaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_MaS, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_MaS))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_MaSV)
                    .addComponent(txt_MaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_MaS)
                    .addComponent(txt_MaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_lamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/refresh.png"))); // NOI18N
        btn_lamMoi.setText("Làm Mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        btn_TaoPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/new-document.png"))); // NOI18N
        btn_TaoPhieu.setText("Tạo Phiếu");

        btn_traSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/return.png"))); // NOI18N
        btn_traSach.setText("Trả Sách");

        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/search-icon.png"))); // NOI18N
        btn_TimKiem.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TaoPhieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_traSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_lamMoi)
                .addGap(18, 18, 18)
                .addComponent(btn_TaoPhieu)
                .addGap(18, 18, 18)
                .addComponent(btn_traSach)
                .addGap(18, 18, 18)
                .addComponent(btn_TimKiem)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        TableBorrowBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Mã Sinh Viên", "Ngày Mượn", "Hạn Trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableBorrowBook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_muonSach)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_muonSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showData(String maSV){
        try {
            TableBorrowBook.removeAll();
            String[] arr = {"Mã Sách", "Mã Sinh Viên", "Ngày Mượn", "Hạn Trả"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            Connection connection = DAO.getConnection();
            String querry = "SELECT * FROM [dbo].[muonSach] WHERE maSV LIKE '%"+ maSV +"%'"+ "ORDER BY ngayMuon";
            PreparedStatement ps = connection.prepareStatement(querry);
            ps.executeQuery();
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MaSach"));
                vector.add(rs.getString("MaSV"));
                vector.add(rs.getString("NgayMuon"));
                vector.add(rs.getString("HanTra"));
                model.addRow(vector);
            }
            TableBorrowBook.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(BorrowBooksManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       showData("");
    }//GEN-LAST:event_formComponentShown

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        reset();
        showData("");
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    public void addAddActionListener(ActionListener log) {
        btn_TaoPhieu.addActionListener(log);
    }
    
    public void addEditActionListener(ActionListener log) {
        btn_traSach.addActionListener(log);
    }
    
    public void addSearchActionListener(ActionListener log) {
        btn_TimKiem.addActionListener(log);
    }
    
    public void addClickTable (MouseListener log){
        TableBorrowBook.addMouseListener(log); 
    }
    
    public void reset(){
        txt_MaSV.setText("");
        txt_MaS.setText("");
    }
    
    public boolean checkRong(){
        if(txt_MaSV.getText().equals("") ||txt_MaS.getText().equals("")){
                return true ;
        }
        return false ;
    }
    
    public BorrowBook getBorrowBook() {       
        BorrowBook BorrowBook = new  BorrowBook();
        BorrowBook.setMaSV(txt_MaSV.getText());
        BorrowBook.setMaS(txt_MaS.getText());       
        return BorrowBook;
    }

    public void setBorrowBook(BorrowBook BorrowBook) {
        txt_MaSV.setText(BorrowBook.getMaSV());
        txt_MaS.setText(BorrowBook.getMaS());               
    }
    
    public BorrowBook getBorrowBookTable(){
        BorrowBook BorrowBook = new  BorrowBook();
        BorrowBook.setMaSV((String) TableBorrowBook.getValueAt(TableBorrowBook.getSelectedRow(), 1));
        BorrowBook.setMaS((String) TableBorrowBook.getValueAt(TableBorrowBook.getSelectedRow(), 0));
        return BorrowBook;
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TableBorrowBook;
    private javax.swing.JButton btn_TaoPhieu;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_traSach;
    private javax.swing.JLabel jB_MaS;
    private javax.swing.JLabel jB_muonSach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jb_MaSV;
    private javax.swing.JTextField txt_MaS;
    private javax.swing.JTextField txt_MaSV;
    // End of variables declaration//GEN-END:variables

}
